import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { getUser } from "@/app/actions/getUser";
import HydrateUser from "@/components/hydrators/HydrateUser";
import RouteLoadingWatcher from "@/components/layout/RouteLoadingWatcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // const user = await getUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen bg-gray-100 dark:bg-gray-950`}
      >
        {/* <HydrateUser initialUser={user} /> */}
        <RouteLoadingWatcher />

        {children}
      </body>
    </html>
  );
}
